/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedNotesIndexRouteImport } from './routes/_authed/notes/index'
import { Route as AuthedNotesNewRouteImport } from './routes/_authed/notes/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNotesIndexRoute = AuthedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesNewRoute = AuthedNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/new': typeof AuthedNotesNewRoute
  '/notes': typeof AuthedNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/new': typeof AuthedNotesNewRoute
  '/notes': typeof AuthedNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/notes/new': typeof AuthedNotesNewRoute
  '/_authed/notes/': typeof AuthedNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/new' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes/new' | '/notes'
  id: '__root__' | '/' | '/_authed' | '/_authed/notes/new' | '/_authed/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/notes/': {
      id: '/_authed/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes/new': {
      id: '/_authed/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthedNotesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedNotesNewRoute: typeof AuthedNotesNewRoute
  AuthedNotesIndexRoute: typeof AuthedNotesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNotesNewRoute: AuthedNotesNewRoute,
  AuthedNotesIndexRoute: AuthedNotesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
